create newsletter template
antistatique/.github pull request #7
Opened 2021-04-14 12:33 UTC by 8uhr

Ajout d'un super template pour organiser une newsletter à envoyer

2021-04-16 06:59 UTC, Yago requested changes

2021-04-16 06:59 UTC, Yago commented on .github/ISSUE_TEMPLATE/newsletter.md
> +title: 'Newsletter'
I just create you a new dedicated label 😉 (you can commit the suggestion) 👇

```suggestion
title: 'Newsletter'
labels: 'type: Newsletter'
```

2021-04-19 06:52 UTC, Yago approved these changes

2021-04-25 09:52 UTC, gido commented
Je suis pas sûr de comprendre, c'est un template pour les newsletter en générale ou pour *notre* newsletter?

2021-04-25 10:39 UTC, 8uhr commented
Les newsletters antistatique et dont Panic !

On Sun, Apr 25, 2021, 11:52 Gilles Doge ***@***.***> wrote:

> Je suis pas sûr de comprendre, c'est un template pour les newsletter en
> générale ou pour *notre* newsletter?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/antistatique/.github/pull/7#issuecomment-826294298>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPWGO7Q6RQMX5E4U3G4QKTTKPQ7BANCNFSM425JTTWA>
> .
>

2023-04-18 15:09 UTC, gido commented
Closing and certainly replaced by Notion or Jira.

2023-04-18 15:09 UTC, closed without merging